### ISSUE TITLE
Permanent change of colour

### ISSUE THREAD

**Issue by AnnoyedUnicorn** [t7hm1/GhostNET#2]
When running the script, it changes the color of the text on the terminal (from white to yellow) and this remains after the script (for all my commands and their returns, until the closing of the terminal).
This happens with all the options of the script.

I'm using it on ArchLinux and I use the Gnome terminal.

Thank you.

**Comment by st-mich43l** [comment]
yeah,it happen to gnome terminal,u may remove color from banner
